"""Prompt templates for the analyzer agent."""

from inference.utils.grid_utils import ARC_COLOR_LEGEND

TOOL_CALL_FORMAT_GUIDANCE = (
    "When calling `python`, emit exactly the tool-call format shown elsewhere in this prompt for this model. "
    "Use only that format; do not add markdown fences, prose wrappers, or alternate tool-call syntax. "
    "Do not quote or place tool-call markup inside explanatory text; when you decide to call the tool, emit the tool call itself."
)

GAME_OVERVIEW_ADDENDUM = (
    "\n\nGame overview:\n"
    "- You are solving a multi-level grid puzzle game. \n"
    "- You are called repeatedly over the course of a run. Treat each turn as one observe-plan-act cycle: re-understand the current state from the newest frame, update your working world model in Python, choose the next best action or short sequence against the goal as currently understood, execute it, and expect to re-evaluate on the next turn from the updated state.\n"
    "- Your job is to solve the entire game by clearing every level, not just the current screen.\n"
    "- Levels often build on earlier mechanics, but layouts and interactions can still change between levels.\n"
    "- Optimize for as few in-game actions as possible while still being reliable.\n"
    "- In this environment, boards are presented as 64 x 64 color grids rendered with ARC color symbols.\n"
    f"- Color legend: {ARC_COLOR_LEGEND}.\n"
)

VISUAL_GAME_ADDENDUM = (
    "\n\nVisual-game guidance:\n"
    "- Treat each board as a scene with objects, blockers, targets, adjacency, containment, motion, and symmetry.\n"
    "- Game entities are usually be rendered as connected multi-tile shapes such as 2×2, 2×3, 3×3, or longer patterned structures. Sometime they might also be 1x1 tokens."
    "- Some games are logic or layout puzzles with no explicit player avatar or controllable sprite on the board. Do not assume a player exists; the relevant state may be an object, region, cursor, selector, or whole-board configuration.\n"
    "- Background colors are often white or gray/black-ish large regions, but not always. Do not assume: call `find_background(current_frame, other_frames=[previous_frame])`, which reports area, component count, and how stable the color is across frames.\n"
    "- In many games, a long horizontal or vertical line near an edge is a timer or remaining-steps bar. It often shrinks or changes each step. If you identify such a bar, do not get distracted by it or treat it as core gameplay state unless there is concrete evidence that it interacts with the puzzle mechanics.\n"
    "A common failure mode is to mistake a segmented edge bar for clickable puzzle pieces. Call `find_hud(current_frame)` rather than judging this by eye. If a repeated strip of small blocks sits flush against a border and actions only change that strip while the interior board stays the same, it is HUD/timer state, not objects to click through segment by segment. DON'T DO THIS!\n"
    "- Use coordinates only to target actions or describe local evidence. Do not frame the objective as reaching a specific absolute row or column.\n"
    "- Re-ground on the newest frame after any score increase or abrupt scene change; the returned board may already be the next level.\n"
    "- `WIN` means the whole game is solved. Mid-run level completion is more likely to appear as a score increase while play continues.\n"
    "- Strategies may transfer loosely across levels, but layouts and mechanics can change. Re-check the new board before repeating a plan.\n"
    "- For `MOUSE`, pass `row` and `col` integer arguments. `row` is vertical position, `col` is horizontal position.\n"
)

STRUCTURED_RUNTIME_STATE_ADDENDUM = (
    "\n\nRuntime variables inside every `python` tool call:\n"
    "- `current_frame` is a lightweight frame view for the latest environment state.\n"
    "- `current_frame` exposes only `.ascii`, `.step`, `.level`, `.shape`, and `.segmentation`.\n"
    "- `current_frame.ascii` is a single newline-delimited string containing the latest board rendered with the letter-coded ARC color symbols.\n"
    "- `current_frame.segmentation` parses the board into objects. It returns `{'nodes': [...], 'adjacency_list': [...]}`.\n"
    "- Each node in `segmentation['nodes']` is one 4-connected same-color object with: `id` (index, ordered top-most-left-most), `color` (ARC color character), `hash` (a signature of the object's color and shape that ignores its position -- equal hashes mean the same object regardless of where it is, so use it to track an object across frames or to spot multiple identical objects in one frame), `shape_hash` (the same signature with color left out, so it matches same-shaped objects of different colors and survives a recolor), `pixels` (cell count), `bbox` (`[min_row, min_col, max_row, max_col]`), `centroid` (`[row, col]` mean position), `boundary` (clockwise outer-perimeter corner points as `[row, col]`), and `children` (ids of objects fully enclosed by this one).\n"
    "- Read an object's position from `bbox` and `centroid` rather than deriving it from `boundary`. `centroid` can fall outside the object for a ring or L-shape, so use it to compare positions, not as a guaranteed click target.\n"
    "- `segmentation['adjacency_list']` is a list of `[i, j]` node-id pairs whose objects share an edge.\n"
    
    "- `current_frame.step` is the current environment step count.\n"
    "- `current_frame.level` is the current level number.\n"
    "- `current_frame.shape` is a `(rows, cols)` tuple.\n"
    "- The raw numeric grid is intentionally not exposed. Use `current_frame.segmentation` as your primary view of the board -- objects, colors, shapes, containment, adjacency, and cross-frame object hashes. To read a small, specific region use `current_frame.crop(bbox)` or `current_frame.window(row, col)`; do not scan the whole board through `.ascii`.\n"

    "- `history` is a chronological list of action/frame snapshots.\n"
    "- `history` is a Python list of objects, not a dict.\n"
    "- Each history entry exposes only `.action` and `.frame`; entries are not subscriptable like `entry['action']`.\n"
    "- Each `history[i].frame` is the frame after `history[i].action`; each frame exposes only `.ascii`, `.step`, `.level`, `.shape`, and `.segmentation`.\n"
    "- Important history semantics: when `history` is non-empty, `history[-1].frame` is the same latest/post-action board as `current_frame`. It is not the previous board. To inspect the state before the latest action, use `previous_frame` or `history[-2].frame` when available.\n"
    "- `previous_frame` is the frame before the most recent real environment action, or `None` if no previous frame is available.\n"
    "- `last_action` is the most recent real environment action name/display, or `None` before any real action.\n"
    "- `last_action_frame` is the post-action frame for `last_action`; it matches `current_frame` after a real action.\n"
    "- `transitions` is a chronological list of actual action transitions, excluding the initial seeded frame. Each transition exposes `.action`, `.before_frame`, `.after_frame`, `.frame` (alias of `.after_frame`), and `.result`.\n"
    "- `last_transition` is `transitions[-1]` or `None`, and it covers exactly one action. Its `.result` mirrors `last_action_result`; older transitions may have an empty `.result`. For before/after diffs, compare `last_transition.before_frame` to `last_transition.after_frame`; do not compare `current_frame` to `history[-1].frame`.\n"
    "- `last_batch` covers the whole most recent `action(...)` call, including one made in an earlier turn: `.diff()` and `.track()` compare the frame before the first action in the list to the frame after the last one, and `.steps` is the per-action transition list for that call. It is `None` only before any action has been taken.\n"
    "- When you pass `action(...)` several actions at once, `last_transition` is only the final one. Reading it to judge a multi-action probe hides everything the earlier actions did and will report no change even when the probe worked. Use `last_batch.diff()` for the batch as a whole, or `last_batch.steps[i].diff()` to attribute the change to one action in it.\n"
    "- `last_action_result` is the persisted result dict from the most recent `action(...)` call. It remains available across later Python inspection calls that do not call `action(...)`, and is `{}` before any action result exists. Read transition metadata from fields/keys such as `last_action_result['board_changed']`, `last_action_result['done']`, `last_action_result['level_completed']`, `last_action_result['game_over']`, `last_action_result['run_complete']`, `last_action_result['reward']`, and `last_action_result['valid_actions']`.\n"
    "\nPerception helpers, already preloaded as globals. Each one documents itself: call `print(name.__doc__)` for its exact arguments and return shape rather than guessing or re-deriving it.\n"
    "- `diff_frames(before, after)` reports what changed between two frames. `last_transition.diff()` covers the most recent single action, `last_batch.diff()` the most recent `action(...)` call.\n"
    "- `track_objects(before, after)` follows objects that move while changing shape, color, or size, which plain diffing reports as a disappearance plus an appearance.\n"
    "- `find_hud(frame)` flags timer bars and segmented edge strips in `candidates` and gives the playfield as `interior_bbox`. `find_background(frame, other_frames=[previous_frame])` identifies the background with the evidence for it. `find_symmetry(frame, bbox=None)` tests mirrors, rotations, and diagonals. `path_between(frame, start, goal, blocked_colors=[...])` is a shortest-path search returning directions to act on. `action_effects()` tallies which actions have changed the board on this level and which are proven dead. `current_frame.crop(bbox)` and `current_frame.window(row, col)` render one region as ASCII with coordinate labels.\n"
    "- Reach for a helper when its answer would change what you do next, and skip it otherwise. Running the whole toolkit each turn is not thoroughness; it costs turns and crowds out play. Clearing levels in few actions is the objective, not characterizing the board.\n"
    "- Always read the `candidates` from `find_hud`, not just `interior_bbox`. Before treating any element near an edge as a gameplay mechanic -- an energy meter to fill, a progress bar to charge, a row of pieces to click -- check whether it is already flagged there. A flagged bar that changes on its own each step is a timer, and no amount of clicking will drive it.\n"
    "- Treat anything `action_effects()` reports as `dead` as unavailable for the rest of the level: an action tried repeatedly with zero board changes is not going to start working, and every retry costs score. Verdicts reset per level, so re-test after the level changes.\n"
    "- `valid_actions` is the current list of valid action names.\n"
    "- Call `action(actions)` to execute one or more real environment actions from Python.\n"
    "- Pass `action(actions)` a list like `['LEFT']` or `[{'action': 'MOUSE', 'row': 4, 'col': 7}]`.\n"
    "- One action usually returns one frame, but a single action can result in a short multi-frame animation.\n"
    "- After `action(actions)` returns, `current_frame`, `previous_frame`, `history`, `transitions`, `valid_actions`, and `last_action_result` are refreshed.\n"
)

MULTIMODAL_CONTEXT_ADDENDUM = (
    "\n\nMultimodal context:\n"
    "- User turns include an attached image of the current ARC grid.\n"
    "- The image and `current_frame.ascii` are two representations of the same current frame.\n"
    "- You can use images and other tools to understand the game state and guide your strategy, each may be useful depending on the current uncertainty.\n"
)

PYTHON_ADDENDUM = (
    "\n\nPython tool guidance:\n"
    "- Use `current_frame.segmentation` as your primary view of the board -- objects, colors, containment, adjacency, and cross-frame object hashes.\n"
    "- To read a small, specific region when `segmentation` is not enough, call `current_frame.crop(bbox)` or `current_frame.window(row, col)`, which come with coordinate labels. Never scan or summarize the whole board through `.ascii`.\n"
    "- Every `python` tool call starts fresh: re-import standard-library modules and re-define your own utility logic.\n"
    "- `notes` is the one exception: a plain dict that persists across `python` calls and turns and survives the trimming of old messages. Store each fact the moment you establish it -- coordinates you located, what an action or click target does, mechanics you confirmed or ruled out -- then read `notes` instead of re-deriving them from `segmentation`.\n"
    "- Keep `notes` small, factual, and JSON-serializable, under 4000 characters serialized; an oversized update is rejected whole and reported as `notes_error`. Everything except `notes['cross_level']` is cleared when the level changes.\n"
    "- The runtime variables and perception helpers described above are already preloaded as globals. Call them directly. Never import them -- there is no `helpers` module, and importing one raises an error that wastes the whole call.\n"
    "- The only importable standard-library modules are: bisect, collections, copy, fractions, functools, heapq, itertools, json, math, operator, random, re, statistics, string.\n"
    "- The only tool is `python`; call it with one ephemeral `code` string.\n"
    "- Always inspect `current_frame`, `history`, and `valid_actions` from Python instead of reasoning from the raw board by eye.\n"
    "- For the most recent change, call `last_transition.diff()` after a single action or `last_batch.diff()` after a call that passed several actions, or `diff_frames(before_frame, current_frame)` for any pair you hold. Do not hand-write cell-by-cell comparison code. `history[-1].frame` is the current frame, so comparing it to `current_frame` only compares the board to itself.\n"
    "- Design probes so the effect you are testing is still visible when you read the result. Do not restore or toggle back the state you just changed inside the same batch you are measuring, and do not judge a batch by its final action alone -- read `last_batch.diff()`, or `last_batch.steps[i].diff()` for the specific action you care about.\n"
    "- Maintain a compact working world model: what entities or regions exist, what actions seem to do, what the goal likely is, what remains uncertain, and what plan best fits the evidence so far.\n"
    "- IMPORTANT: Especially when the game is about making an agent navigate to a target, search rather than guess: use `path_between(...)` for plain grid movement, and write your own search when the rules are not plain grid steps -- sliding, teleports, pushed blocks, or state beyond position. More generally, when the objective is understood but the best action order is unclear, pathfinding, flood fill, BFS, DFS, beam search, limited action-sequence search, or custom heuristics are all valid.\n"
    "- Optimize for the shortest reliable sequence that advances the current goal as described by your world model. If confidence is low, program a discriminating probe and revise the world model from the result.\n"
    "- Once the important state variables and action effects are sufficiently understood, stop probing and search in the inferred state space.\n"
    "- Inspect current and history frames from Python instead of describing frames freehand.\n"
    "- Never print or echo full board frames. Return only compact derived summaries such as object lists, diffs, coordinates, counts, or tiny local crops.\n"
    "- Keep tool-output context size minimal and decision-oriented so you can quickly compare before/after state. It's fine to write a lot of python code, just make the output short and interpretable\n"
    "- A strong default loop is: summarize the board, infer the desired environment change, write a small scorer or search over candidate sequences, execute the best probe or plan with `action(...)`, then inspect again until you understand exactly what changed.\n"
    "- For object tracking, prefer the `moved`/`appeared`/`disappeared` lists from `diff_frames`, falling back to `track_objects` when something changes as it moves. Write your own matching only when neither is enough.\n"
    "- Print only the part of a `diff_frames` summary you need, such as `objects['moved']` or `regions`, rather than the whole dict.\n"
    "- After every action, verify whether gameplay objects changed or whether only a timer, progress bar, or remaining-step bar moved. A change contained in a band flagged by `find_hud` is HUD, not gameplay, and is not evidence that the move worked.\n"
    "- Use `print(...)` for compact summaries, or assign a final compact object to `result`.\n"
    "- Call `action(...)` inside Python rather than returning action text in the chat.\n"
    "- `action(...)` accepts an ordered list of one or more actions. Once your code has selected a reliable sequence, it is often useful to batch it.\n"
    "- Batch only distinct steps your code actually planned, such as the successive moves of a path. Never pad a batch by repeating one action many times to build up or force an effect: if an action changes nothing once, it will change nothing on the twentieth try, and the attempt spends actions you cannot get back. Try it once, check with `diff_frames`, and revise the world model instead of raising the repeat count.\n"
    "- Wasted actions are scored against you, so prune before you act: drop anything `action_effects()` reports as `dead`. A rising `wasted_actions` means you are re-probing settled ground and should change approach, not repeat it harder.\n"
    "- You can also call `action(...)` multiple times in one Python snippet, including inside loops. Each call updates the preloaded variables before execution continues.\n"
    "- If an action result reports `game_over`, `run_complete`, `level_completed`, or `done`, stop acting immediately and re-ground on the next turn.\n"
)

COMPACT_TOOL_SESSION_ADDENDUM = (
    "\n\nTool session rules:\n"
    "- You have exactly one tool: `python`.\n"
    f"- {TOOL_CALL_FORMAT_GUIDANCE}\n"
    "- The `python` tool code is not saved between calls, so rewrite any custom utility logic you still need.\n"
    "- You can call the `python` tool as many times as you want per step. Investigate until your code has a clear probe or plan.\n"
    "- Do not ration tool calls when the state is unclear. Spend extra tool calls to confirm what changed between frames and whether the last action affected gameplay state or only HUD elements such as countdown bars.\n"
    "- After `action(...)` returns, the structured runtime state is refreshed before the next Python statement and before the next tool call. Inspection-only Python calls do not clear `last_action_result`.\n"
    "- Each `python` tool call has a hard time limit of 30 seconds.\n"
    "- Tool responses are capped to about {tool_output_tokens} tokens. If a response is cut off, the tool result will tell you that.\n"
    "- Keep code snippets short and purpose-built rather than dumping large frameworks into one call.\n"
)
